---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    monitor: prometheus
    scrape: pull
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9090
      nodePort: 30909
